default:
  raw_data_path: "./data/raw"
  processed_data_path: "./data/processed"
  x_path: "x.pt"
  edge_path: "edge.pt"

datasets:
  wiki:
    dataset: 'wiki'
    data_path: "wikipedia.csv"


  yelp:
    dataset: 'yelp'

models:
  dgnn:
    model: 'dgnn'
    lr: 1e-3
    dgnn_hidden_dim: 128
    dgnn_output_dim: 128

  pdgnn:
    model: 'pdgnn'